spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:~/test1
    username: sa
    password:
  cook:
    count: 180
security:
  basic:
    enabled: true

